(() => {
  'use strict';

  const BUILD = '20260910-1625';
  const PRIORITIES = ['Alta','Media','Baja'];
  const MONTHS = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
  const RESPONSIBLE = {
    preparedBy:'Mgs. Jefferson Villarreal', preparedRole:'Gestor de Procesos Académicos',
    reviewedBy:'Ing. Martha Tomalá', reviewedRole:'Coordinadora General de Carreras',
    approvedBy:'Dr. Alex León', approvedRole:'Vicerrector'
  };

  const clean = v => String(v ?? '').trim();
  const norm = v => clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ');
  const pct = (a,b) => b ? a*100/b : 0;
  const pctText = n => Number(n||0).toLocaleString('es-EC',{maximumFractionDigits:1})+'%';
  const naturalList = items => {
    const list=(items||[]).filter(Boolean);
    if(!list.length)return'';
    if(list.length===1)return list[0];
    if(list.length===2)return list[0]+' y '+list[1];
    return list.slice(0,-1).join(', ')+' y '+list[list.length-1];
  };

  function periodText(){
    const fmt=v=>{const m=clean(v).match(/^(\d{4})-(\d{2})/);return m?(MONTHS[Number(m[2])-1]||m[2])+' '+m[1]:clean(v);};
    const a=fmt(state?.period?.start),b=fmt(state?.period?.end);
    return a&&b?a+' a '+b:(a||b||'Período seleccionado');
  }

  function docCode(){
    if(typeof syncPeriodCodes==='function')syncPeriodCodes(state.period);
    return clean(state?.period?.dnfCode)||'UGPA-RGI1-01-PRO-31';
  }

  function fileName(){
    const code=docCode(),title='Detección de Necesidades de Formación';
    if(typeof documentPdfFilename==='function')return documentPdfFilename(code,title);
    return code+' - '+title+'.pdf';
  }

  function careerStatus(name){
    const k=typeof careerKey==='function'?careerKey(name):norm(name);
    return clean(state?.section7?.careerStatus?.[k]?.status)||'Inactiva';
  }

  function activeCareers(){
    return (state?.careers||[]).filter(c=>careerStatus(c.name)==='Activa');
  }

  function needRows(){
    const careers=activeCareers(),rows=[];
    careers.forEach((career,ci)=>{
      const coord=(state?.coordinations||[]).find(c=>norm(c.carrera)===norm(career.name));
      const items=Array.isArray(coord?.needItems)?coord.needItems:[];
      items.filter(i=>clean(i?.text)).forEach((item,ni)=>rows.push({
        code:clean(item.dnfCode)||('DNF-'+String(ci+1).padStart(2,'0')+'-'+String(ni+1).padStart(2,'0')),
        career:clean(career.name),program:clean(career.program),need:clean(item.text),
        priority:PRIORITIES.includes(clean(item.priorityOverride))?clean(item.priorityOverride):'Media'
      }));
    });
    return rows;
  }

  const THEMES = [
    {name:'Tecnología educativa, IA y transformación digital',rx:/(inteligencia artificial|\bia\b|digital|tecnolog|software|automat|analit|datos|crm|api|nube|virtualiz|ciberseg|ux\/ui|prototip|electr[oó]nic|herramientas digitales)/i},
    {name:'Investigación, innovación y evidencia',rx:/(investig|innov|evidencia|cient[ií]fica|transferencia|an[aá]lisis de evidencias)/i},
    {name:'Currículo, didáctica y evaluación',rx:/(curr[ií]cul|did[aá]ctic|evaluaci[oó]n|aprendizaje|competenc|metodolog|planificaci[oó]n de experiencias|enseñanza)/i},
    {name:'Gestión, liderazgo y toma de decisiones',rx:/(gesti[oó]n|liderazgo|indicador|estrat[eé]g|talento humano|financier|negociaci[oó]n|ventas|marketing|comercio electr[oó]nico)/i},
    {name:'Normativa, seguridad, riesgo y cumplimiento',rx:/(normativ|seguridad|riesgo|bioseguridad|niif|tribut|inocuidad|peligro|control|cumplimiento|protocolo)/i},
    {name:'Salud, bienestar y práctica clínica',rx:/(enfermer|cl[ií]nic|paciente|rehabilit|biomec[aá]nic|terap[eé]ut|est[eé]tic|movimiento humano)/i}
  ];
  function themeFor(text){return THEMES.find(t=>t.rx.test(clean(text)))?.name||'Formación disciplinar específica';}
  function countBy(rows,getter){const out={};rows.forEach(r=>{const k=clean(getter(r))||'Sin información';out[k]=(out[k]||0)+1;});return out;}

  function genericLines(){
    const a=(Array.isArray(state?.section6?.genericLines)?state.section6.genericLines:[]).map(v=>typeof v==='string'?clean(v):clean(v?.name)).filter(Boolean);
    if(a.length)return a;
    const b=(state?.settings?.genericLines||[]).map(clean).filter(Boolean);
    return b.length?b:['Educación Superior, Pedagogía y Didáctica','Evaluación del Aprendizaje y Formación por Competencias','Investigación e Innovación Educativa','Tecnología Educativa e Inteligencia Artificial','Currículo y Gestión Académica','Inclusión, Diversidad y Atención Educativa'];
  }

  const GENERIC_DETAILS = {
    'Educación Superior, Pedagogía y Didáctica':['Fortalece la mediación pedagógica y la capacidad de transformar el conocimiento disciplinar en experiencias de aprendizaje pertinentes.','Didáctica de educación superior, planificación de clase, metodologías activas y acompañamiento del aprendizaje.','Aplicación transversal en todas las carreras, especialmente cuando la necesidad específica exige fortalecer la práctica docente.'],
    'Evaluación del Aprendizaje y Formación por Competencias':['Favorece la coherencia entre resultados de aprendizaje, actividades, evidencias y criterios de evaluación.','Diseño de instrumentos, rúbricas, evaluación auténtica, retroalimentación y análisis de resultados.','Complementa las necesidades que requieran fortalecer evaluación, desempeño práctico y formación por competencias.'],
    'Investigación e Innovación Educativa':['Fortalece la generación y uso de evidencia para mejorar docencia, innovación y toma de decisiones académicas.','Metodología de investigación, investigación aplicada, escritura académica, innovación y transferencia de resultados.','Se vincula con necesidades que demandan mayor capacidad investigativa o incorporación sistemática de innovación.'],
    'Tecnología Educativa e Inteligencia Artificial':['Responde a la transformación digital de los procesos académicos y al uso responsable de herramientas de inteligencia artificial.','Entornos virtuales, recursos digitales, IA generativa, analítica y criterios de uso ético y seguro.','Complementa necesidades disciplinares cuando la tecnología modifica la forma de enseñar, evaluar, investigar o gestionar.'],
    'Currículo y Gestión Académica':['Asegura coherencia entre perfil de egreso, resultados de aprendizaje, planificación y gestión de los procesos académicos.','Diseño y actualización curricular, microcurrículo, planificación académica, indicadores y mejora continua.','Pertinente para necesidades relacionadas con actualización de contenidos, articulación curricular y gestión de calidad académica.'],
    'Inclusión, Diversidad y Atención Educativa':['Favorece prácticas académicas accesibles, inclusivas y pertinentes para una población estudiantil diversa.','Diseño universal para el aprendizaje, adaptaciones, accesibilidad, diversidad y estrategias de acompañamiento.','Se activa cuando las necesidades específicas implican barreras de aprendizaje, diversidad o atención educativa diferenciada.']
  };

  const BIBLIOGRAPHY = [
    'Asamblea Nacional del Ecuador. (2008). Constitución de la República del Ecuador. Registro Oficial Suplemento 449.',
    'Asamblea Nacional del Ecuador. Ley Orgánica de Educación Superior (LOES), texto vigente utilizado como sustento normativo del proceso.',
    'Consejo de Educación Superior. Reglamento de Carrera y Escalafón del Personal Académico del Sistema de Educación Superior, codificación vigente utilizada en el proceso.',
    'Consejo de Aseguramiento de la Calidad de la Educación Superior. (2024). Modelo de evaluación externa con fines de acreditación para los institutos superiores técnicos y tecnológicos. CACES.',
    'Instituto Superior Tecnológico Quito Metropolitano. (2023). Plan Estratégico de Desarrollo Institucional 2023–2030. ITSQMET.',
    'Instituto Superior Tecnológico Quito Metropolitano. Plan Operativo Anual del período correspondiente.',
    'Instituto Superior Tecnológico Quito Metropolitano. Reglamento institucional de formación docente vigente.',
    'Instituto Superior Tecnológico Quito Metropolitano. Manual del proceso de formación académica vigente.',
    'Organización de Estados Iberoamericanos para la Educación, la Ciencia y la Cultura. (2020). Formación docente en Iberoamérica: claves para una estrategia regional. OEI.',
    'Tenti Fanfani, E. (2007). El oficio de docente: vocación, trabajo y profesión en el siglo XXI. Siglo XXI Editores.',
    'UNESCO. (2019). Marco de competencias de los docentes en materia de TIC. Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura.',
    'Vaillant, D. (2015). La formación de docentes en América Latina: repensar el desarrollo profesional en clave de aprendizaje. Fondo de Cultura Económica.',
    'Vaillant, D., & Marcelo, C. (2015). Desarrollo profesional docente: ¿cómo se aprende a enseñar? Narcea Ediciones.',
    'Zabalza, M. A. (2007). Competencias docentes del profesorado universitario: calidad y desarrollo profesional. Narcea Ediciones.',
    'Marcelo, C. (2009). La profesionalización docente y su impacto en la mejora de la educación. Revista de Educación, 349, 79–108.',
    'Tobón, S. (2013). Formación basada en competencias: pensamiento complejo, currículo, didáctica y evaluación. Ecoe Ediciones.'
  ];

  function emit(percent,phase,extra={}){window.dispatchEvent(new CustomEvent('docformacion-pdf-progress',{detail:{type:'dnf',percent,phase,build:BUILD,...extra}}));}
  function downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function rgb(hex){const h=hex.replace('#','');return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)];}

  function createWriter(){
    if(!window.jspdf?.jsPDF)throw new Error('No se cargó el motor PDF. Recarga la aplicación.');
    const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4',orientation:'portrait',compress:true,putOnlyUsedFonts:true,precision:2});
    const pageW=210,pageH=297,left=18,right=18,top=45,bottom=18,bodyW=pageW-left-right;let y=top;const sectionPages={},tocRows=[];let tocPage=0;
    function logoData(){try{return typeof INSTITUTION_LOGO_DATA==='string'?INSTITUTION_LOGO_DATA:'';}catch(_e){return'';}}
    function drawHeader(){const x=15,w=180,h=27,a=45,b=90,c=45,yy=12;doc.setDrawColor(70);doc.setLineWidth(.25);doc.rect(x,yy,w,h);doc.line(x+a,yy,x+a,yy+h);doc.line(x+a+b,yy,x+a+b,yy+h);doc.line(x+a,yy+8,x+a+b,yy+8);const logo=logoData();if(logo){try{doc.addImage(logo,'JPEG',x+8,yy+7,a-16,h-14,undefined,'FAST');}catch(_e){doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('ITSQMET',x+a/2,yy+h/2,{align:'center'});}}else{doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('ITSQMET',x+a/2,yy+h/2,{align:'center'});}doc.setTextColor(35);doc.setFont('helvetica','normal');doc.setFontSize(7.1);doc.text('UNIDAD DE GESTIÓN DE PROCESOS ACADÉMICOS',x+a+b/2,yy+5.2,{align:'center'});doc.setFont('helvetica','bold');doc.setFontSize(7.2);doc.text('Detección de Necesidades de Formación',x+a+b/2,yy+14,{align:'center'});doc.setFontSize(6.8);doc.text(periodText(),x+a+b/2,yy+22.8,{align:'center'});doc.setFont('helvetica','bold');doc.setFontSize(7);doc.text('Código:',x+a+b+c/2,yy+11,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(6.7);doc.text(doc.splitTextToSize(docCode(),c-6),x+a+b+c/2,yy+16,{align:'center'});}
    function newPage(){doc.addPage();drawHeader();y=top;}function ensure(h){if(y+h>pageH-bottom)newPage();}function startMajor(){if(y>top+12)newPage();}
    function heading(text,level=1){const size=level===1?13:level===2?11:9.7,before=level===1?5:3,after=level===1?4:2;if(level===1){const m=clean(text).match(/^(\d+)/);if(m&&!sectionPages[m[1]])sectionPages[m[1]]=doc.getNumberOfPages();}doc.setFont('helvetica','bold');doc.setFontSize(size);doc.setTextColor(25);const lines=doc.splitTextToSize(clean(text),bodyW);ensure(before+lines.length*5+after+3);y+=before;doc.text(lines,left,y,{lineHeightFactor:1.12});y+=lines.length*5+after;}
    function paragraph(text,opts={}){const size=opts.size||9.4,indent=opts.indent===false?0:5,lineH=opts.lineH||4.75;doc.setFont('helvetica',opts.bold?'bold':'normal');doc.setFontSize(size);doc.setTextColor(opts.muted?85:30);const lines=doc.splitTextToSize(clean(text),bodyW-indent);lines.forEach((line,i)=>{ensure(lineH);doc.text(line,left+(i===0?indent:0),y,{maxWidth:bodyW-(i===0?indent:0)});y+=lineH;});y+=opts.after==null?2.2:opts.after;}
    function bullet(text,opts={}){const size=opts.size||9.2,lineH=4.6;doc.setFont('helvetica','normal');doc.setFontSize(size);doc.setTextColor(30);const lines=doc.splitTextToSize(clean(text),bodyW-8);lines.forEach((line,i)=>{ensure(lineH);if(i===0)doc.text('•',left+1,y);doc.text(line,left+6,y);y+=lineH;});y+=1;}
    function labelParagraph(label,text){const combined=clean(label)+' '+clean(text);doc.setFont('helvetica','normal');doc.setFontSize(9.3);doc.setTextColor(30);const lines=doc.splitTextToSize(combined,bodyW-5);lines.forEach((line,i)=>{ensure(4.7);doc.text(line,left+(i===0?5:0),y);y+=4.7;});y+=2;}
    function table(headers,rows,weights,opts={}){const total=(weights||headers.map(()=>1)).reduce((a,b)=>a+b,0),widths=(weights||headers.map(()=>1)).map(v=>bodyW*v/total),fontSize=opts.fontSize||7.5,pad=1.4,lineH=opts.lineH||3.25;const wrap=(text,w,style='normal')=>{doc.setFont('helvetica',style);doc.setFontSize(fontSize);return doc.splitTextToSize(clean(text)||' ',Math.max(4,w-pad*2));};const rowH=(row,style='normal')=>Math.max(...row.map((cell,i)=>wrap(cell,widths[i],style).length))*lineH+pad*2;function draw(row,head=false,bold=false){const h=rowH(row,head||bold?'bold':'normal');ensure(h);let x=left;if(head){doc.setFillColor(55,55,55);doc.rect(left,y,bodyW,h,'F');}else if(opts.striped&&opts._rowIndex%2===1){doc.setFillColor(247,248,249);doc.rect(left,y,bodyW,h,'F');}doc.setDrawColor(135);doc.setLineWidth(.16);row.forEach((cell,i)=>{doc.rect(x,y,widths[i],h);doc.setFont('helvetica',head||bold?'bold':'normal');doc.setFontSize(fontSize);doc.setTextColor(head?255:25);doc.text(wrap(cell,widths[i],head||bold?'bold':'normal'),x+pad,y+pad+2.4,{lineHeightFactor:1.05});x+=widths[i];});doc.setTextColor(25);y+=h;}draw(headers,true,true);rows.forEach((r,i)=>{opts._rowIndex=i;const row=Array.isArray(r)?r:r.cells;const h=rowH(row,r.bold?'bold':'normal');if(y+h>pageH-bottom){newPage();draw(headers,true,true);}draw(row,false,!!r.bold);});y+=3;}
    function note(text){doc.setFont('helvetica','italic');doc.setFontSize(7.7);doc.setTextColor(85);const lines=doc.splitTextToSize(clean(text),bodyW);lines.forEach(line=>{ensure(3.9);doc.text(line,left,y);y+=3.9;});y+=2;}
    function cover(){drawHeader();doc.setTextColor(30);doc.setFont('helvetica','bold');doc.setFontSize(19);const title=doc.splitTextToSize('Detección de Necesidades de Formación',150);doc.text(title,pageW/2,116,{align:'center',lineHeightFactor:1.15});doc.setFontSize(14);doc.text(periodText(),pageW/2,116+title.length*8+9,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(80);doc.text('Documento institucional de diagnóstico, priorización y trazabilidad',pageW/2,158,{align:'center'});const x=15,w=180,col=60,yy=238,row1=20,row2=10,row3=13,total=row1+row2+row3;doc.setDrawColor(80);doc.rect(x,yy,w,total);doc.line(x,yy+row1,x+w,yy+row1);doc.line(x,yy+row1+row2,x+w,yy+row1+row2);doc.line(x+col,yy,x+col,yy+total);doc.line(x+col*2,yy,x+col*2,yy+total);const entries=[['ELABORADO POR:',RESPONSIBLE.preparedBy,RESPONSIBLE.preparedRole],['REVISADO POR:',RESPONSIBLE.reviewedBy,RESPONSIBLE.reviewedRole],['APROBADO POR:',RESPONSIBLE.approvedBy,RESPONSIBLE.approvedRole]];entries.forEach((r,i)=>{const cx=x+i*col;doc.setFont('helvetica','bold');doc.setFontSize(7.1);doc.setTextColor(35);doc.text(r[0],cx+3,yy+5);doc.setFontSize(6.5);doc.text('ÁREA DE FIRMA / QR DIGITAL',cx+col/2,yy+13,{align:'center'});doc.setFont('helvetica','normal');doc.text('NOMBRE: '+r[1],cx+3,yy+row1+6);doc.text(doc.splitTextToSize('CARGO: '+r[2],col-6),cx+3,yy+row1+row2+5,{lineHeightFactor:1.05});});newPage();}
    function toc(){tocPage=doc.getNumberOfPages();heading('Índice General');const entries=['1. Introducción','2. Base Legal','3. Alineación Estratégica','4. Metodología y Enfoque','5. Caracterización del Diagnóstico','6. Líneas de Formación por Coordinación Académica','7. Cobertura Institucional','8. Resumen Ejecutivo','9. Conclusiones','10. Recomendaciones','11. Bibliografía','12. Anexos'];doc.setFont('helvetica','normal');doc.setFontSize(9.5);entries.forEach((t,i)=>{ensure(7);doc.text(t,left,y);tocRows.push({section:String(i+1),y,page:tocPage});doc.setTextColor(140);doc.text('................................................',135,y);doc.setTextColor(30);y+=7;});newPage();}
    function donutCard(title,data,noteText){const h=72;ensure(h+5);const x=left,w=bodyW,yy=y;doc.setFillColor(248,250,252);doc.setDrawColor(220);doc.roundedRect(x,yy,w,h,3,3,'FD');doc.setFont('helvetica','bold');doc.setFontSize(9.2);doc.setTextColor(35);doc.text(title,x+4,yy+7);const total=data.reduce((s,d)=>s+d.value,0)||1,colors=['#5B73F2','#E00078','#2AA3A3','#9067C6','#7AA241','#D78A2C'];let ly=yy+18;data.forEach((d,i)=>{const c=rgb(colors[i%colors.length]);doc.setFillColor(...c);doc.circle(x+6,ly-1.2,1.3,'F');doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.setTextColor(50);doc.text(d.label,x+10,ly);doc.setFont('helvetica','bold');doc.text(String(d.value)+' · '+pctText(pct(d.value,total)),x+66,ly);ly+=7;});const cx=x+w-38,cy=yy+35,r=18,segments=120;let cursor=0;doc.setLineCap?.('round');data.forEach((d,i)=>{const c=rgb(colors[i%colors.length]);doc.setDrawColor(...c);doc.setLineWidth(5.3);const count=Math.round((d.value/total)*segments);for(let s=0;s<count;s++){const a1=-Math.PI/2+((cursor+s)/segments)*Math.PI*2,a2=-Math.PI/2+((cursor+s+.78)/segments)*Math.PI*2;doc.line(cx+Math.cos(a1)*r,cy+Math.sin(a1)*r,cx+Math.cos(a2)*r,cy+Math.sin(a2)*r);}cursor+=count;});doc.setTextColor(40);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(String(total),cx,cy+1,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(6.5);doc.text('registros',cx,cy+6,{align:'center'});if(noteText){doc.setFont('helvetica','italic');doc.setFontSize(6.8);doc.setTextColor(90);doc.text(doc.splitTextToSize(noteText,w-8),x+4,yy+h-8,{lineHeightFactor:1.05});}y+=h+5;}
    function wordCloudCard(title,words){const h=82;ensure(h+5);const x=left,w=bodyW,yy=y;doc.setFillColor(248,250,252);doc.setDrawColor(220);doc.roundedRect(x,yy,w,h,3,3,'FD');doc.setFont('helvetica','bold');doc.setFontSize(9.2);doc.setTextColor(35);doc.text(title,x+4,yy+7);const positions=[[12,25],[72,22],[125,28],[38,40],[96,43],[142,47],[15,57],[60,61],[111,61],[145,66],[42,73],[92,75]];words.slice(0,12).forEach((word,i)=>{const [px,py]=positions[i]||[10+(i%4)*40,25+Math.floor(i/4)*15],size=Math.max(7,15-i*.6);doc.setFont('helvetica',i<3?'bold':'normal');doc.setFontSize(size);doc.setTextColor(55+(i%4)*18,75+(i%3)*20,150+(i%2)*40);doc.text(word.label,x+px,yy+py);});y+=h+5;}
    function conclusion(no,title,text){heading(no+'. '+title,2);paragraph(text,{indent:false});}
    function finish(){const total=doc.getNumberOfPages();if(tocPage){doc.setPage(tocPage);doc.setFont('helvetica','bold');doc.setFontSize(9.5);doc.setTextColor(35);tocRows.forEach(r=>doc.text(String(sectionPages[r.section]||'—'),190,r.y,{align:'right'}));}for(let p=1;p<=total;p++){doc.setPage(p);doc.setFillColor(255);doc.rect(0,pageH-13,pageW,13,'F');doc.setTextColor(105);doc.setFont('helvetica','normal');doc.setFontSize(6.7);doc.text('ITSQMET · Unidad de Gestión de Procesos Académicos · '+periodText()+' · Página '+p+' de '+total,pageW/2,pageH-8,{align:'center'});}doc.setProperties({title:'Detección de Necesidades de Formación',subject:periodText(),author:'ITSQMET'});const blob=doc.output('blob');if(!blob?.size)throw new Error('El PDF se generó vacío.');downloadBlob(blob,fileName());return{ok:true,downloaded:true,pages:total,size:blob.size,filePath:fileName()};}
    return{doc,cover,toc,startMajor,newPage,heading,paragraph,bullet,labelParagraph,table,note,donutCard,wordCloudCard,conclusion,finish};
  }

  function topWords(rows){const stop=new Set('actualizacion fortalecimiento aplicacion herramientas herramienta uso para con del de la las los el en y una un al por que procesos proceso formacion carrera carreras docente docentes institucional aprendizaje gestion basada basado sobre nuevas nuevo area areas'.split(/\s+/)),map=new Map();rows.forEach(r=>clean(r.need).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-zñ0-9\s]/g,' ').split(/\s+/).forEach(w=>{if(w.length<5||stop.has(w))return;map.set(w,(map.get(w)||0)+1);}));return[...map.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'es')).slice(0,12).map(([label,value])=>({label:label.charAt(0).toUpperCase()+label.slice(1),value}));}

  function renderRichDnf(w){
    const rows=needRows(),active=activeCareers(),generic=genericLines(),byPriority=countBy(rows,r=>r.priority),byProgram=countBy(active,r=>r.program),byTheme=countBy(rows,r=>themeFor(r.need)),byCareer=countBy(rows,r=>r.career);
    const diagnosed=new Set(rows.map(r=>norm(r.career))).size,coverage=pct(diagnosed,active.length),high=byPriority.Alta||0,medium=byPriority.Media||0,low=byPriority.Baja||0;
    const themeRanking=Object.entries(byTheme).sort((a,b)=>b[1]-a[1]),topThemes=themeRanking.slice(0,4).map(x=>x[0]),careerCounts=Object.entries(byCareer).sort((a,b)=>b[1]-a[1]),countsUniform=careerCounts.length>1&&new Set(careerCounts.map(x=>x[1])).size===1;

    w.heading('1. Introducción');
    w.paragraph('La formación y el desarrollo profesional del personal académico constituyen componentes permanentes de la calidad de la educación superior. La actualización disciplinar, pedagógica, tecnológica e investigativa permite responder a cambios en los campos profesionales, a nuevas formas de enseñanza y evaluación y a las necesidades institucionales de mejora continua. Desde esta perspectiva, la detección de necesidades de formación no se limita a registrar temas de interés, sino que organiza evidencia para orientar decisiones de planificación, priorización y seguimiento.');
    w.paragraph('En el ámbito de la educación superior, el desarrollo profesional docente demanda procesos sistemáticos que articulen las competencias requeridas por la institución con las características de su oferta académica. La literatura utilizada como referencia institucional enfatiza la profesionalización, la formación por competencias, el uso pedagógico de tecnologías y la actualización continua como dimensiones relevantes del trabajo docente (Zabalza, 2007; Marcelo, 2009; Tobón, 2013; UNESCO, 2019; Vaillant & Marcelo, 2015).');
    w.paragraph('En este marco, el ITSQMET desarrolla la Detección de Necesidades de Formación correspondiente al período '+periodText()+'. Para este documento la unidad de análisis es la necesidad de formación asociada a cada carrera activa. La información variable se obtiene de las plantillas institucionales de Carreras y DNF y se valida antes de incorporarse al informe.');
    w.paragraph('El diagnóstico resultante permite reconocer brechas y prioridades específicas, identificar convergencias entre carreras, mantener líneas intelectuales genéricas de alcance transversal y asegurar trazabilidad mediante códigos DNF. Cada código constituye el vínculo entre el diagnóstico, el Plan de Formación, el seguimiento y el posterior Informe de Cumplimiento, de modo que los documentos del proceso conserven continuidad entre períodos y eviten duplicidades.');

    w.heading('2. Base Legal');
    w.paragraph('La Detección de Necesidades de Formación se sustenta en disposiciones nacionales, referentes de aseguramiento de la calidad e instrumentos institucionales que vinculan el perfeccionamiento académico con la planificación y la mejora continua. Para la generación del documento se mantienen como referencias las fuentes normativas e institucionales utilizadas por el proceso.');
    w.heading('2.1. Normativa constitucional, legal y reglamentaria nacional',2);
    w.labelParagraph('Constitución de la República del Ecuador.','El marco constitucional de la educación superior orienta el sistema hacia la formación académica y profesional, la investigación, la innovación y la generación y difusión del conocimiento. Este fundamento justifica que el fortalecimiento de capacidades del personal académico se integre a los procesos institucionales de calidad.');
    w.labelParagraph('Ley Orgánica de Educación Superior (LOES).','Las disposiciones relacionadas con calidad, aseguramiento de la calidad y perfeccionamiento permanente del personal académico respaldan la identificación periódica de necesidades y su transformación en acciones planificadas.');
    w.labelParagraph('Reglamento de Carrera y Escalafón del Personal Académico del Sistema de Educación Superior.','El perfeccionamiento y la capacitación del personal académico deben responder a requerimientos institucionales, objetivos y resultados de evaluación. La DNF constituye el insumo técnico para organizar estos requerimientos antes de la formulación del Plan de Formación.');
    w.heading('2.2. Referentes del CACES',2);w.labelParagraph('Modelo de Evaluación Externa 2024 para Institutos Superiores Técnicos y Tecnológicos.','El indicador relacionado con formación académica en curso y capacitación requiere evidencias de planificación articulada con necesidades específicas y genéricas del cuerpo académico. La DNF permite documentar esa relación y demostrar continuidad entre diagnóstico, planificación, ejecución y seguimiento.');
    w.heading('2.3. Normativa e instrumentos institucionales del ITSQMET',2);
    w.labelParagraph('Plan Estratégico de Desarrollo Institucional (PEDI).','Orienta el fortalecimiento del talento humano y la mejora de los procesos académicos, proporcionando el marco estratégico para priorizar acciones de desarrollo profesional.');
    w.labelParagraph('Plan Operativo Anual (POA).','Permite traducir las prioridades detectadas en actividades, responsables, recursos, metas e indicadores verificables durante el período.');
    w.labelParagraph('Reglamento institucional de formación docente.','Establece las reglas, responsabilidades y mecanismos institucionales vinculados a la formación, capacitación y perfeccionamiento académico.');
    w.labelParagraph('Manual del proceso de formación académica.','Organiza la secuencia DNF → Plan de Formación → Seguimiento → Informe de Cumplimiento y determina la necesidad de conservar trazabilidad entre los registros asociados.');

    w.heading('3. Alineación Estratégica');
    w.paragraph('La DNF se integra a la planificación institucional y no opera como un registro aislado. Los resultados obtenidos deben utilizarse para orientar decisiones de formación, articularlas con la gestión académica y convertirlas posteriormente en acciones verificables dentro del Plan de Formación Docente.');
    w.heading('3.1. Vinculación con el PEDI',2);w.paragraph('El diagnóstico se relaciona con el fortalecimiento del talento humano y con la mejora continua de los procesos académicos. Su aporte consiste en identificar qué capacidades requieren fortalecimiento, en qué carreras se localizan y qué nivel de prioridad presentan, de forma que las decisiones de formación respondan a necesidades concretas y no únicamente a ofertas disponibles.');
    ['Identificar brechas de formación específicas por carrera y necesidades transversales de alcance institucional.','Definir trayectorias de formación coherentes con los perfiles profesionales, la oferta académica y los objetivos de desarrollo institucional.','Vincular la formación con procesos de actualización curricular, innovación pedagógica, investigación aplicada y transformación digital.'].forEach(w.bullet);
    w.heading('3.2. Vinculación con el POA',2);w.paragraph('Los resultados de la DNF constituyen insumos para programar actividades, establecer responsables y distribuir recursos. La UGPA articula la consolidación documental del proceso; la Coordinación General de Carreras y las coordinaciones académicas aportan la lectura de necesidades por carrera; y las unidades institucionales responsables de talento humano, calidad y planificación pueden utilizar los resultados para programar apoyos, seguimiento y evaluación.');
    w.heading('3.3. Alineación con procesos académicos institucionales',2);w.paragraph('Las necesidades detectadas se relacionan con procesos de construcción y actualización curricular, seguimiento a la calidad académica y mejora de la práctica docente. Cuando una necesidad se vincula con resultados de aprendizaje, metodología, evaluación, tecnología o actualización disciplinar, su atención debe reflejarse en acciones del Plan y posteriormente en evidencias de aplicación.');
    w.heading('3.4. Coherencia con el modelo de acreditación',2);w.paragraph('La DNF aporta evidencia a una lógica sistémica de calidad: planificación institucional, gestión académica, desarrollo del personal, condiciones para el aprendizaje y resultados del proceso formativo. Su valor no reside únicamente en disponer de una lista de cursos, sino en demostrar que las decisiones de formación parten de necesidades verificables, se priorizan y posteriormente pueden ser evaluadas.');

    w.heading('4. Metodología y Enfoque');
    w.paragraph('El diagnóstico adopta un enfoque institucional, descriptivo y de priorización. La información se organiza por carrera y se consolida mediante plantillas estructuradas, con reglas de validación que impiden incorporar registros incompletos, duplicados o incompatibles con el catálogo activo del período.');
    w.heading('4.1. Objetivo General',2);w.paragraph('Identificar, organizar y priorizar las necesidades de formación de las carreras activas del ITSQMET durante el período '+periodText()+', generando información trazable que sustente la formulación del Plan de Formación Docente.');
    w.heading('4.2. Objetivos Específicos',2);['Consolidar el catálogo de carreras activas y su nivel de formación para el período.','Registrar necesidades concretas de formación por carrera, evitando duplicidades y formulaciones genéricas sin correspondencia académica.','Clasificar cada necesidad según prioridad Alta, Media o Baja.','Identificar convergencias temáticas entre carreras para reconocer oportunidades de formación transversal.','Mantener un código DNF persistente que permita enlazar diagnóstico, Plan, seguimiento e Informe de Cumplimiento.'].forEach(w.bullet);
    w.heading('4.3. Unidad de análisis',2);w.paragraph('La unidad de análisis es cada necesidad concreta de formación asociada a una carrera activa. El documento no requiere nombres, cédulas ni expedientes individuales de docentes para habilitar el diagnóstico; el análisis se concentra en necesidades institucionales por carrera.');
    w.heading('4.4. Cobertura del diagnóstico',2);w.paragraph('El período registra '+active.length+' carrera(s) activa(s). Se identificaron necesidades en '+diagnosed+' carrera(s), lo que corresponde a una cobertura diagnóstica de '+pctText(coverage)+'.');
    w.heading('4.5. Fuentes e instrumento de levantamiento',2);w.paragraph('Se utilizan dos plantillas Excel independientes. La plantilla de Carreras define el catálogo oficial del período, su nivel de formación y estado Activa/Inactiva. Una vez validada, la plantilla DNF se habilita únicamente con las carreras activas y permite registrar una o varias necesidades con su prioridad.');
    w.heading('4.6. Variables analizadas',2);['Carrera activa y nivel de formación.','Necesidad de formación formulada para la carrera.','Prioridad institucional de la necesidad.','Código DNF para trazabilidad.','Tema convergente derivado del contenido de las necesidades.'].forEach(w.bullet);
    w.heading('4.7. Criterio de prioridad',2);w.paragraph('La prioridad se registra en tres niveles: Alta, Media y Baja. La clasificación permite distinguir las necesidades que requieren atención preferente en el Plan de Formación de aquellas que pueden programarse en una etapa posterior o mediante acciones complementarias.');
    w.heading('4.8. Validación de información',2);w.paragraph('Antes de aplicar una carga, la app valida la estructura del archivo, la existencia de carreras activas, coincidencia con el catálogo, duplicados, necesidades vacías y valores de prioridad. Si existen errores, el archivo completo se rechaza y no se aplica información parcialmente.');
    w.heading('4.9. Consolidación',2);w.paragraph('Las filas válidas se consolidan por carrera. Para cada necesidad se conserva un código DNF único y persistente. Los totales y porcentajes presentados en las secciones de resultados se calculan directamente desde la misma base, evitando que un indicador tenga valores diferentes en distintas partes del documento.');
    w.heading('4.10. Análisis de convergencia',2);w.paragraph('Las necesidades se agrupan temáticamente mediante reglas de clasificación basadas en su contenido textual. Esta lectura permite detectar asuntos recurrentes entre carreras y orientar acciones transversales sin sustituir las necesidades específicas registradas en cada coordinación académica.');

    w.heading('5. Caracterización del Diagnóstico');
    w.paragraph('La caracterización describe el alcance, la composición de la oferta diagnosticada, la distribución de prioridades y los principales patrones temáticos. Los indicadores se calculan automáticamente a partir de la información del período activo.');
    w.table(['Indicador','Resultado'],[['Carreras activas',String(active.length)],['Carreras diagnosticadas',String(diagnosed)],['Cobertura diagnóstica',pctText(coverage)],['Necesidades específicas registradas',String(rows.length)],['Necesidades de prioridad Alta',String(high)],['Necesidades de prioridad Media',String(medium)],['Necesidades de prioridad Baja',String(low)],['Líneas genéricas institucionales',String(generic.length)]],[68,32],{fontSize:8.4,striped:true});
    w.heading('5.1. Distribución de carreras por nivel de formación',2);w.table(['Nivel de formación','Carreras activas','Porcentaje'],Object.entries(byProgram).map(([p,c])=>[p,String(c),pctText(pct(c,active.length))]),[55,22,23],{fontSize:8.2,striped:true});
    const dominantPrograms=Object.entries(byProgram).sort((a,b)=>b[1]-a[1]);if(dominantPrograms.length)w.paragraph('La oferta activa se concentra principalmente en '+dominantPrograms[0][0]+', con '+dominantPrograms[0][1]+' carrera(s), equivalente a '+pctText(pct(dominantPrograms[0][1],active.length))+'. Esta distribución debe considerarse al planificar acciones institucionales de alcance general y al estimar la demanda potencial de formación.');
    w.heading('5.2. Distribución de necesidades por prioridad',2);w.table(['Prioridad','Necesidades','Porcentaje'],PRIORITIES.map(p=>[p,String(byPriority[p]||0),pctText(pct(byPriority[p]||0,rows.length))]),[45,25,30],{fontSize:8.3,striped:true});
    w.paragraph('La prioridad Alta representa '+pctText(pct(high,rows.length))+' de las necesidades registradas. '+(high>medium+low?'Esto evidencia una concentración significativa de requerimientos que deben ser considerados de atención preferente en la formulación del Plan de Formación.':'La distribución observada requiere equilibrar acciones inmediatas con otras de programación progresiva según la disponibilidad institucional.'));
    w.heading('5.3. Distribución de necesidades por carrera',2);w.table(['Carrera','Necesidades','Alta','Media','Baja'],active.map(c=>{const cr=rows.filter(r=>norm(r.career)===norm(c.name)),cp=countBy(cr,r=>r.priority);return[c.name,String(cr.length),String(cp.Alta||0),String(cp.Media||0),String(cp.Baja||0)];}),[52,12,12,12,12],{fontSize:7.5,striped:true});
    w.paragraph(countsUniform?'La cantidad de necesidades registradas es homogénea entre las carreras. Por tanto, la priorización institucional no debe realizarse por volumen, sino principalmente por nivel de prioridad y por convergencia temática.':'La cantidad de necesidades varía entre carreras; esta diferencia debe interpretarse junto con la prioridad asignada y no únicamente como volumen de requerimientos.');
    w.heading('5.4. Convergencias temáticas',2);w.table(['Tema convergente','Necesidades','Porcentaje'],themeRanking.map(([t,c])=>[t,String(c),pctText(pct(c,rows.length))]),[62,18,20],{fontSize:7.8,striped:true});if(topThemes.length)w.paragraph('Las principales convergencias se ubican en '+naturalList(topThemes)+'. Estas recurrencias permiten identificar oportunidades de formación transversal, siempre conservando el vínculo de cada acción con la necesidad específica y su código DNF.');

    w.startMajor();w.heading('6. Líneas de Formación por Coordinación Académica');w.paragraph('Las líneas específicas se presentan por carrera. Cada subsección mantiene la necesidad originalmente registrada, su prioridad y una orientación de planificación derivada de los datos del período. No se sustituyen ni se inventan necesidades adicionales.');
    active.forEach((career,index)=>{const cr=rows.filter(r=>norm(r.career)===norm(career.name)),cp=countBy(cr,r=>r.priority),themes=[...new Set(cr.map(r=>themeFor(r.need)))];w.heading('6.'+(index+1)+'. '+career.name,2);w.paragraph('Para la carrera '+career.name+' se registraron '+cr.length+' necesidad(es) específica(s): '+(cp.Alta||0)+' de prioridad Alta, '+(cp.Media||0)+' Media y '+(cp.Baja||0)+' Baja. El análisis temático muestra énfasis en '+naturalList(themes)+'.');w.table(['Código','Necesidad específica','Prioridad','Tema convergente'],cr.map(r=>[r.code,r.need,r.priority,themeFor(r.need)]),[16,48,13,23],{fontSize:7.2,striped:true});w.heading('Orientación para el Plan de Formación',3);w.paragraph(((cp.Alta||0)>0?'Las necesidades clasificadas como Alta deben trasladarse prioritariamente al Plan de Formación, definiendo para cada código una acción concreta, modalidad, cronograma, indicador, meta, responsable y medio de verificación. ':'')+((cp.Media||0)>0?'Las necesidades de prioridad Media pueden programarse de forma progresiva o articularse con acciones transversales cuando exista convergencia con otras carreras. ':'')+'La planificación debe conservar el CODIGO_DNF como identificador de trazabilidad.');});
    w.heading('6.'+(active.length+1)+'. Formación Intelectual Genérica',2);w.paragraph('Además de las necesidades específicas, el ITSQMET mantiene líneas de formación intelectual genérica de aplicación transversal. Estas líneas no reemplazan las necesidades por carrera; funcionan como un marco común para fortalecer capacidades pedagógicas, investigativas, tecnológicas, curriculares e inclusivas.');w.table(['Línea genérica','Justificación','Alcance','Aplicación institucional'],generic.map(line=>{const d=GENERIC_DETAILS[line]||['Línea transversal definida institucionalmente.','Aplicación según necesidades del período.','Complementa las necesidades específicas sin sustituirlas.'];return[line,d[0],d[1],d[2]];}),[22,27,25,26],{fontSize:6.7,striped:true});

    w.heading('7. Cobertura Institucional');w.paragraph('La cobertura institucional considera las carreras marcadas como activas para el período '+periodText()+'. El catálogo constituye la población de referencia para el diagnóstico y permite verificar que ninguna carrera activa quede sin necesidades registradas.');
    w.heading('7.1. Listado oficial de carreras activas',2);w.table(['Carrera','Nivel de formación','Estado'],active.map(c=>[c.name,c.program,'Activa']),[52,33,15],{fontSize:7.7,striped:true});
    w.heading('7.2. Resumen por nivel de formación',2);w.table(['Nivel','Cantidad','Porcentaje'],Object.entries(byProgram).map(([p,c])=>[p,String(c),pctText(pct(c,active.length))]),[55,20,25],{fontSize:8.2,striped:true});
    w.heading('7.3. Cobertura diagnóstica',2);w.paragraph('De '+active.length+' carreras activas, '+diagnosed+' cuentan con necesidades registradas. La cobertura diagnóstica alcanza '+pctText(coverage)+'. '+(coverage===100?'Esto confirma que el análisis incorpora la totalidad del catálogo activo del período.':'Las carreras pendientes deben completarse antes de considerar cerrado el diagnóstico institucional.'));

    w.heading('8. Resumen Ejecutivo');w.paragraph('El presente informe consolida la Detección de Necesidades de Formación del ITSQMET correspondiente al período '+periodText()+'. El diagnóstico cubre '+diagnosed+' de '+active.length+' carreras activas y registra '+rows.length+' necesidades específicas, organizadas por prioridad y vinculadas mediante códigos DNF persistentes.');w.paragraph('La distribución de prioridades muestra '+high+' necesidades de nivel Alta ('+pctText(pct(high,rows.length))+'), '+medium+' de nivel Media ('+pctText(pct(medium,rows.length))+') y '+low+' de nivel Baja ('+pctText(pct(low,rows.length))+'). Esta lectura permite distinguir las acciones que requieren incorporación preferente en el Plan de Formación de aquellas que pueden programarse progresivamente.');if(countsUniform)w.paragraph('El número de necesidades por carrera es homogéneo, por lo que la comparación entre coordinaciones no debe basarse en cantidad. La diferenciación relevante se encuentra en la prioridad de cada necesidad y en los temas que convergen entre carreras.');if(topThemes.length)w.paragraph('Los temas con mayor convergencia corresponden a '+naturalList(topThemes)+'. Estos patrones constituyen oportunidades para diseñar acciones transversales, siempre que cada acción mantenga la trazabilidad con los códigos DNF que la originan.');
    w.heading('Indicadores cuantitativos clave',2);w.table(['Indicador','Resultado'],[['Cobertura diagnóstica',pctText(coverage)],['Carreras activas',String(active.length)],['Carreras diagnosticadas',String(diagnosed)],['Necesidades específicas',String(rows.length)],['Prioridad Alta',String(high)+' · '+pctText(pct(high,rows.length))],['Prioridad Media',String(medium)+' · '+pctText(pct(medium,rows.length))],['Prioridad Baja',String(low)+' · '+pctText(pct(low,rows.length))],['Líneas genéricas',String(generic.length)]],[65,35],{fontSize:8.4,striped:true});
    w.heading('Líneas de acción estratégica',2);w.table(['Línea','Objetivo'],[['Plan de Formación por carrera','Transformar las necesidades priorizadas en acciones concretas, medibles y trazables por CODIGO_DNF.'],['Acciones transversales','Aprovechar las convergencias temáticas para organizar formación común sin perder la especificidad de cada carrera.'],['Fortalecimiento de capacidades','Atender prioritariamente las necesidades clasificadas como Alta y programar progresivamente las de prioridad Media y Baja.'],['Seguimiento y evidencia','Vincular cada acción a indicadores, metas, responsables y medios de verificación que posteriormente alimenten el Informe de Cumplimiento.'],['Retroalimentación','Utilizar los resultados del Informe de Cumplimiento como insumo del siguiente ciclo de detección de necesidades.']],[35,65],{fontSize:7.5,striped:true});

    w.heading('9. Conclusiones');w.conclusion(1,'La cobertura institucional permite sustentar el diagnóstico.','La DNF incorporó '+diagnosed+' de '+active.length+' carreras activas, equivalente a '+pctText(coverage)+' de cobertura. Esta amplitud permite utilizar los resultados como base institucional para la planificación del período, dado que las necesidades se encuentran vinculadas al catálogo oficial de carreras activas.');w.conclusion(2,'La prioridad de las necesidades orienta la toma de decisiones.','Se identificaron '+rows.length+' necesidades específicas, de las cuales '+high+' corresponden a prioridad Alta, '+medium+' a Media y '+low+' a Baja. La presencia de '+pctText(pct(high,rows.length))+' de necesidades de prioridad Alta evidencia la conveniencia de concentrar recursos y acciones del Plan en los requerimientos de atención preferente.');w.conclusion(3,'Las convergencias temáticas permiten complementar la atención por carrera.','El análisis de contenido evidencia recurrencias en '+naturalList(topThemes)+'. Estas convergencias permiten organizar acciones compartidas entre carreras cuando resulte pertinente, sin sustituir las necesidades específicas ni perder la trazabilidad de los códigos que las originan.');w.conclusion(4,'La trazabilidad fortalece la continuidad del proceso.','El uso de CODIGO_DNF permite mantener una relación verificable entre la necesidad diagnosticada, la acción incorporada al Plan de Formación, su seguimiento y el resultado consignado en el Informe de Cumplimiento. Esta continuidad reduce duplicidades y facilita la revisión de cada ciclo.');w.conclusion(5,'La formación debe combinar respuestas específicas y líneas transversales.','La diversidad de campos profesionales de las carreras exige acciones diferenciadas, mientras que las líneas genéricas institucionales permiten atender capacidades comunes relacionadas con pedagogía, evaluación, investigación, tecnología, currículo e inclusión. Ambos niveles deben coexistir dentro de la planificación institucional.');

    w.heading('10. Recomendaciones');w.heading('Lineamientos iniciales para el Plan de Formación Docente',2);['Diseñar el Plan de Formación del período utilizando como base directa las necesidades validadas y su CODIGO_DNF.','Priorizar las necesidades de nivel Alta y definir para cada una acciones, modalidad, cronograma, indicador, meta, responsable, verificación y recursos.','Articular necesidades convergentes mediante acciones transversales cuando ello mejore eficiencia y pertinencia, conservando el vínculo individual con cada código DNF.','Alinear las acciones con el perfil de egreso, la actualización disciplinar, los procesos curriculares y las prioridades institucionales de calidad.'].forEach(w.bullet);w.heading('Propuesta de criterios para asignación de apoyos',2);['Considerar como criterio principal la prioridad de la necesidad, su impacto académico y la posibilidad de beneficiar a varias carreras.','Diferenciar los mecanismos de apoyo según duración, modalidad, costo, disponibilidad institucional y resultados esperados de la acción formativa.','Exigir que los apoyos institucionales queden vinculados a evidencias verificables y a compromisos de aplicación o transferencia del conocimiento adquirido.','Favorecer acciones relacionadas con las convergencias temáticas identificadas cuando puedan generar un efecto institucional amplio sin desatender necesidades disciplinares específicas.'].forEach(w.bullet);w.heading('Consideraciones para el efecto multiplicador y seguimiento',2);['Establecer productos o evidencias de aplicación del aprendizaje, tales como mejoras curriculares, recursos didácticos, talleres internos, innovaciones metodológicas o productos académicos.','Realizar seguimiento por CODIGO_DNF y acción planificada, evitando crear identificadores nuevos que rompan la trazabilidad.','Consolidar periódicamente el estado de avance, los medios de verificación y los resultados alcanzados.','Utilizar las brechas de ejecución y las acciones no completadas como insumo explícito para el diagnóstico del siguiente período.'].forEach(w.bullet);

    w.heading('11. Bibliografía');w.paragraph('Se incluyen las fuentes normativas, institucionales y académicas utilizadas como marco de referencia del documento. La app debe mantener una sola entrada por fuente y conservar únicamente aquellas que formen parte del contenido generado para el período.',{indent:false});BIBLIOGRAPHY.forEach(r=>w.bullet(r,{size:8.4}));

    w.startMajor();w.heading('12. Anexos');w.heading('12.1. Matriz de trazabilidad DNF',2);w.table(['Código','Carrera','Necesidad resumida','Prioridad','Tema convergente'],rows.map(r=>[r.code,r.career,r.need,r.priority,themeFor(r.need)]),[14,22,38,10,16],{fontSize:6.5,striped:true});w.heading('12.2. Matriz de Formación Intelectual Genérica',2);w.table(['Línea genérica','Justificación','Alcance','Aplicación'],generic.map(line=>{const d=GENERIC_DETAILS[line]||['Línea transversal definida institucionalmente.','Aplicación según necesidades del período.','Complementa las necesidades específicas.'];return[line,d[0],d[1],d[2]];}),[23,27,25,25],{fontSize:6.5,striped:true});
    w.startMajor();w.heading('12.3. Evidencias gráficas del diagnóstico',2);w.paragraph('Los siguientes anexos presentan los resultados con un formato visual tipo formulario/resumen, construido automáticamente desde los datos válidos del período. No son capturas manuales y se actualizan cada vez que cambian las plantillas.');w.donutCard('Distribución de necesidades por prioridad',PRIORITIES.map(p=>({label:p,value:byPriority[p]||0})),'Total de necesidades específicas: '+rows.length+'. Los porcentajes se calculan sobre registros válidos del período.');w.donutCard('Distribución de carreras por nivel de formación',Object.entries(byProgram).map(([label,value])=>({label,value})),'Total de carreras activas: '+active.length+'.');w.donutCard('Cobertura diagnóstica',[{label:'Carreras diagnosticadas',value:diagnosed},{label:'Carreras pendientes',value:Math.max(0,active.length-diagnosed)}],'Cobertura calculada sobre el catálogo de carreras activas del período.');w.wordCloudCard('Términos recurrentes en las necesidades registradas',topWords(rows));w.note('Nota: la nube de términos se obtiene mediante conteo automático de palabras relevantes en las necesidades registradas; se excluyen conectores y expresiones genéricas de alta frecuencia.');
  }

  async function buildRichDnf(){emit(2,'starting');await new Promise(r=>setTimeout(r,0));const rows=needRows();if(!rows.length)throw new Error('No existen necesidades DNF para generar el documento.');emit(8,'preparing');const w=createWriter();w.cover();w.toc();emit(18,'render',{stage:'content'});renderRichDnf(w);emit(92,'assembling');await new Promise(r=>setTimeout(r,0));const result=w.finish();emit(100,'done');return result;}

  const previousGenerateDocument=typeof generateDocument==='function'?generateDocument:null;
  generateDocument=async function richDocumentGenerate(type){if(type!=='dnf'){if(previousGenerateDocument)return previousGenerateDocument(type);throw new Error('No está disponible el generador del documento solicitado.');}const status=typeof documentStatus==='function'?documentStatus('dnf'):{ready:true};if(!status.ready){if(typeof toast==='function')toast('Completa las plantillas pendientes antes de generar el PDF');return;}const button=document.getElementById('generateCurrent')||document.querySelector('[data-generate="dnf"]'),old=button?.textContent||'Generar PDF';if(button){button.disabled=true;button.textContent='Generando PDF…';}window.__DOCFORMACION_ACTIVE_PDF_TYPE='dnf';try{const result=await buildRichDnf();if(result?.ok&&typeof toast==='function')toast('PDF institucional completo generado correctamente');return result;}catch(error){console.error('[DocFormación] DNF completa:',error);emit(0,'error',{message:error?.message||String(error)});if(typeof toast==='function')toast('Error al generar PDF: '+(error?.message||error));return{ok:false,error:error?.message||String(error)};}finally{if(button){button.disabled=false;button.textContent=old;}setTimeout(()=>{if(window.__DOCFORMACION_ACTIVE_PDF_TYPE==='dnf')window.__DOCFORMACION_ACTIVE_PDF_TYPE='';},1200);}};

  window.__DOCFORMACION_DNF_RICH_DOCUMENT='v4';window.__DOCFORMACION_DNF_RICH_BUILD=BUILD;
})();
